name: Test setup-youtube-dl
on:
  push:
    paths:
      - action.yml
      - .github/workflows/test.yml
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ffmpeg: [ffmpeg-false, ffmpeg-true]
        
    steps:
      - name: Setup FFmpeg
        if: ${{ matrix.ffmpeg == 'ffmpeg-true' }}
        uses: FedericoCarboni/setup-ffmpeg@v1
        
      - name: Setup youtube-dl using setup-youtube-dl
        uses: AnimMouse/setup-youtube-dl@main
        
      - name: Test youtube-dl installed by setup-youtube-dl
        run: youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc