name: Test setup-youtube-dl
on:
  push:
    paths:
      - action.yaml
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ffmpeg: [without-ffmpeg, with-ffmpeg]
        
    steps:
      - name: Setup FFmpeg
        if: ${{ matrix.ffmpeg == 'with-ffmpeg' }}
        uses: FedericoCarboni/setup-ffmpeg@v1
        
      - name: Setup youtube-dl using setup-youtube-dl
        uses: AnimMouse/setup-youtube-dl@main
        
      - name: Test youtube-dl installed by setup-youtube-dl
        run: youtube-dl https://www.youtube.com/watch?v=BaW_jenozKc
        
      - name: List files
        run: ls