name: Test setup-youtube-dl
on:
  push:
    paths:
      - action.yml
      - scripts/**
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Setup youtube-dl using setup-youtube-dl
        uses: AnimMouse/setup-youtube-dl@main
        
      - name: Test youtube-dl by checking version
        run: youtube-dl --version